# azure-pipelines.yml

pool:
  vmImage: 'ubuntu-18.04'

steps:
  - script: |
      docker pull loadimpact/k6
    displayName: Pull k6 image
  - script: |
      docker run -i \
        -v `pwd`/../:/src \
        loadimpact/k6 \
        /src/003_basic_test/http_get.js \
    displayName: Run k6 cloud